// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.zpb.protobuf.test.user;

public interface NickNameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.zpb.protobuf.proto.user.NickName)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string nickName = 6;</code>
   * @return The nickName.
   */
  String getNickName();
  /**
   * <code>string nickName = 6;</code>
   * @return The bytes for nickName.
   */
  com.google.protobuf.ByteString
      getNickNameBytes();
}
