// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.zpb.protobuf.test.user;

/**
 * <pre>
 *创建一个 User 对象
 * </pre>
 *
 * Protobuf type {@code com.zpb.protobuf.proto.user.User}
 */
public final class User extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.zpb.protobuf.proto.user.User)
    UserOrBuilder {
private static final long serialVersionUID = 0L;
  // Use User.newBuilder() to construct.
  private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private User() {
    name_ = "";
    strLing_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    list_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new User();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private User(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 16: {

            age_ = input.readInt32();
            break;
          }
          case 29: {

            price_ = input.readFloat();
            break;
          }
          case 33: {

            salary_ = input.readDouble();
            break;
          }
          case 40: {

            isDeleted_ = input.readBool();
            break;
          }
          case 50: {
            String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 74: {
            NickName.Builder subBuilder = null;
            if (nickName_ != null) {
              subBuilder = nickName_.toBuilder();
            }
            nickName_ = input.readMessage(NickName.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(nickName_);
              nickName_ = subBuilder.buildPartial();
            }

            break;
          }
          case 82: {
            String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              strLing_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            strLing_.add(s);
            break;
          }
          case 90: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              list_ = new java.util.ArrayList<com.zpb.protobuf.test.demo.Demo>();
              mutable_bitField0_ |= 0x00000002;
            }
            list_.add(
                input.readMessage(com.zpb.protobuf.test.demo.Demo.parser(), extensionRegistry));
            break;
          }
          case 98: {
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              strMap_ = com.google.protobuf.MapField.newMapField(
                  StrMapDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000004;
            }
            com.google.protobuf.MapEntry<String, String>
            strMap__ = input.readMessage(
                StrMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            strMap_.getMutableMap().put(
                strMap__.getKey(), strMap__.getValue());
            break;
          }
          case 106: {
            if (!((mutable_bitField0_ & 0x00000008) != 0)) {
              objMap_ = com.google.protobuf.MapField.newMapField(
                  ObjMapDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000008;
            }
            com.google.protobuf.MapEntry<String, UserMapPO>
            objMap__ = input.readMessage(
                ObjMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            objMap_.getMutableMap().put(
                objMap__.getKey(), objMap__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        strLing_ = strLing_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        list_ = java.util.Collections.unmodifiableList(list_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return UserOutClass.internal_static_com_zpb_protobuf_proto_user_User_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 12:
        return internalGetStrMap();
      case 13:
        return internalGetObjMap();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return UserOutClass.internal_static_com_zpb_protobuf_proto_user_User_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            User.class, Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <pre>
   * int64
   * </pre>
   *
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  @Override
  public long getId() {
    return id_;
  }

  public static final int AGE_FIELD_NUMBER = 2;
  private int age_;
  /**
   * <pre>
   * int32
   * </pre>
   *
   * <code>int32 age = 2;</code>
   * @return The age.
   */
  @Override
  public int getAge() {
    return age_;
  }

  public static final int PRICE_FIELD_NUMBER = 3;
  private float price_;
  /**
   * <pre>
   * float
   * </pre>
   *
   * <code>float price = 3;</code>
   * @return The price.
   */
  @Override
  public float getPrice() {
    return price_;
  }

  public static final int SALARY_FIELD_NUMBER = 4;
  private double salary_;
  /**
   * <pre>
   * double
   * </pre>
   *
   * <code>double salary = 4;</code>
   * @return The salary.
   */
  @Override
  public double getSalary() {
    return salary_;
  }

  public static final int ISDELETED_FIELD_NUMBER = 5;
  private boolean isDeleted_;
  /**
   * <pre>
   * bool
   * </pre>
   *
   * <code>bool isDeleted = 5;</code>
   * @return The isDeleted.
   */
  @Override
  public boolean getIsDeleted() {
    return isDeleted_;
  }

  public static final int NAME_FIELD_NUMBER = 6;
  private volatile Object name_;
  /**
   * <pre>
   * String
   * </pre>
   *
   * <code>string name = 6;</code>
   * @return The name.
   */
  @Override
  public String getName() {
    Object ref = name_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * String
   * </pre>
   *
   * <code>string name = 6;</code>
   * @return The bytes for name.
   */
  @Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    Object ref = name_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NICKNAME_FIELD_NUMBER = 9;
  private NickName nickName_;
  /**
   * <pre>
   * 对象中引用-对象
   * </pre>
   *
   * <code>.com.zpb.protobuf.proto.user.NickName nickName = 9;</code>
   * @return Whether the nickName field is set.
   */
  @Override
  public boolean hasNickName() {
    return nickName_ != null;
  }
  /**
   * <pre>
   * 对象中引用-对象
   * </pre>
   *
   * <code>.com.zpb.protobuf.proto.user.NickName nickName = 9;</code>
   * @return The nickName.
   */
  @Override
  public NickName getNickName() {
    return nickName_ == null ? NickName.getDefaultInstance() : nickName_;
  }
  /**
   * <pre>
   * 对象中引用-对象
   * </pre>
   *
   * <code>.com.zpb.protobuf.proto.user.NickName nickName = 9;</code>
   */
  @Override
  public NickNameOrBuilder getNickNameOrBuilder() {
    return getNickName();
  }

  public static final int STRLING_FIELD_NUMBER = 10;
  private com.google.protobuf.LazyStringList strLing_;
  /**
   * <pre>
   * 对象中引用-List&lt;string&gt;
   * </pre>
   *
   * <code>repeated string strLing = 10;</code>
   * @return A structure.list containing the strLing.
   */
  public com.google.protobuf.ProtocolStringList
      getStrLingList() {
    return strLing_;
  }
  /**
   * <pre>
   * 对象中引用-List&lt;string&gt;
   * </pre>
   *
   * <code>repeated string strLing = 10;</code>
   * @return The count of strLing.
   */
  public int getStrLingCount() {
    return strLing_.size();
  }
  /**
   * <pre>
   * 对象中引用-List&lt;string&gt;
   * </pre>
   *
   * <code>repeated string strLing = 10;</code>
   * @param index The index of the element to return.
   * @return The strLing at the given index.
   */
  public String getStrLing(int index) {
    return strLing_.get(index);
  }
  /**
   * <pre>
   * 对象中引用-List&lt;string&gt;
   * </pre>
   *
   * <code>repeated string strLing = 10;</code>
   * @param index The index of the value to return.
   * @return The bytes of the strLing at the given index.
   */
  public com.google.protobuf.ByteString
      getStrLingBytes(int index) {
    return strLing_.getByteString(index);
  }

  public static final int LIST_FIELD_NUMBER = 11;
  private java.util.List<com.zpb.protobuf.test.demo.Demo> list_;
  /**
   * <pre>
   * 对象中引用-List&lt;Object&gt;
   * </pre>
   *
   * <code>repeated .com.zpb.protobuf.proto.demo.Demo List = 11;</code>
   */
  @Override
  public java.util.List<com.zpb.protobuf.test.demo.Demo> getListList() {
    return list_;
  }
  /**
   * <pre>
   * 对象中引用-List&lt;Object&gt;
   * </pre>
   *
   * <code>repeated .com.zpb.protobuf.proto.demo.Demo List = 11;</code>
   */
  @Override
  public java.util.List<? extends com.zpb.protobuf.test.demo.DemoOrBuilder>
      getListOrBuilderList() {
    return list_;
  }
  /**
   * <pre>
   * 对象中引用-List&lt;Object&gt;
   * </pre>
   *
   * <code>repeated .com.zpb.protobuf.proto.demo.Demo List = 11;</code>
   */
  @Override
  public int getListCount() {
    return list_.size();
  }
  /**
   * <pre>
   * 对象中引用-List&lt;Object&gt;
   * </pre>
   *
   * <code>repeated .com.zpb.protobuf.proto.demo.Demo List = 11;</code>
   */
  @Override
  public com.zpb.protobuf.test.demo.Demo getList(int index) {
    return list_.get(index);
  }
  /**
   * <pre>
   * 对象中引用-List&lt;Object&gt;
   * </pre>
   *
   * <code>repeated .com.zpb.protobuf.proto.demo.Demo List = 11;</code>
   */
  @Override
  public com.zpb.protobuf.test.demo.DemoOrBuilder getListOrBuilder(
      int index) {
    return list_.get(index);
  }

  public static final int STRMAP_FIELD_NUMBER = 12;
  private static final class StrMapDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        String, String> defaultEntry =
            com.google.protobuf.MapEntry
            .<String, String>newDefaultInstance(
                UserOutClass.internal_static_com_zpb_protobuf_proto_user_User_StrMapEntry_descriptor,
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      String, String> strMap_;
  private com.google.protobuf.MapField<String, String>
  internalGetStrMap() {
    if (strMap_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          StrMapDefaultEntryHolder.defaultEntry);
    }
    return strMap_;
  }

  public int getStrMapCount() {
    return internalGetStrMap().getMap().size();
  }
  /**
   * <pre>
   * 对象中引用-Map&lt;string,string&gt;
   * </pre>
   *
   * <code>map&lt;string, string&gt; strMap = 12;</code>
   */

  @Override
  public boolean containsStrMap(
      String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetStrMap().getMap().containsKey(key);
  }
  /**
   * Use {@link #getStrMapMap()} instead.
   */
  @Override
  @Deprecated
  public java.util.Map<String, String> getStrMap() {
    return getStrMapMap();
  }
  /**
   * <pre>
   * 对象中引用-Map&lt;string,string&gt;
   * </pre>
   *
   * <code>map&lt;string, string&gt; strMap = 12;</code>
   */
  @Override

  public java.util.Map<String, String> getStrMapMap() {
    return internalGetStrMap().getMap();
  }
  /**
   * <pre>
   * 对象中引用-Map&lt;string,string&gt;
   * </pre>
   *
   * <code>map&lt;string, string&gt; strMap = 12;</code>
   */
  @Override

  public String getStrMapOrDefault(
      String key,
      String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<String, String> map =
        internalGetStrMap().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * 对象中引用-Map&lt;string,string&gt;
   * </pre>
   *
   * <code>map&lt;string, string&gt; strMap = 12;</code>
   */
  @Override

  public String getStrMapOrThrow(
      String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<String, String> map =
        internalGetStrMap().getMap();
    if (!map.containsKey(key)) {
      throw new IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int OBJMAP_FIELD_NUMBER = 13;
  private static final class ObjMapDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        String, UserMapPO> defaultEntry =
            com.google.protobuf.MapEntry
            .<String, UserMapPO>newDefaultInstance(
                UserOutClass.internal_static_com_zpb_protobuf_proto_user_User_ObjMapEntry_descriptor,
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                UserMapPO.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      String, UserMapPO> objMap_;
  private com.google.protobuf.MapField<String, UserMapPO>
  internalGetObjMap() {
    if (objMap_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ObjMapDefaultEntryHolder.defaultEntry);
    }
    return objMap_;
  }

  public int getObjMapCount() {
    return internalGetObjMap().getMap().size();
  }
  /**
   * <pre>
   * 对象中引用-Map&lt;string,Object&gt;
   * </pre>
   *
   * <code>map&lt;string, .com.zpb.protobuf.proto.user.UserMapPO&gt; objMap = 13;</code>
   */

  @Override
  public boolean containsObjMap(
      String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetObjMap().getMap().containsKey(key);
  }
  /**
   * Use {@link #getObjMapMap()} instead.
   */
  @Override
  @Deprecated
  public java.util.Map<String, UserMapPO> getObjMap() {
    return getObjMapMap();
  }
  /**
   * <pre>
   * 对象中引用-Map&lt;string,Object&gt;
   * </pre>
   *
   * <code>map&lt;string, .com.zpb.protobuf.proto.user.UserMapPO&gt; objMap = 13;</code>
   */
  @Override

  public java.util.Map<String, UserMapPO> getObjMapMap() {
    return internalGetObjMap().getMap();
  }
  /**
   * <pre>
   * 对象中引用-Map&lt;string,Object&gt;
   * </pre>
   *
   * <code>map&lt;string, .com.zpb.protobuf.proto.user.UserMapPO&gt; objMap = 13;</code>
   */
  @Override

  public UserMapPO getObjMapOrDefault(
      String key,
      UserMapPO defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<String, UserMapPO> map =
        internalGetObjMap().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * 对象中引用-Map&lt;string,Object&gt;
   * </pre>
   *
   * <code>map&lt;string, .com.zpb.protobuf.proto.user.UserMapPO&gt; objMap = 13;</code>
   */
  @Override

  public UserMapPO getObjMapOrThrow(
      String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<String, UserMapPO> map =
        internalGetObjMap().getMap();
    if (!map.containsKey(key)) {
      throw new IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (age_ != 0) {
      output.writeInt32(2, age_);
    }
    if (Float.floatToRawIntBits(price_) != 0) {
      output.writeFloat(3, price_);
    }
    if (Double.doubleToRawLongBits(salary_) != 0) {
      output.writeDouble(4, salary_);
    }
    if (isDeleted_ != false) {
      output.writeBool(5, isDeleted_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, name_);
    }
    if (nickName_ != null) {
      output.writeMessage(9, getNickName());
    }
    for (int i = 0; i < strLing_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, strLing_.getRaw(i));
    }
    for (int i = 0; i < list_.size(); i++) {
      output.writeMessage(11, list_.get(i));
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetStrMap(),
        StrMapDefaultEntryHolder.defaultEntry,
        12);
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetObjMap(),
        ObjMapDefaultEntryHolder.defaultEntry,
        13);
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (age_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, age_);
    }
    if (Float.floatToRawIntBits(price_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, price_);
    }
    if (Double.doubleToRawLongBits(salary_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, salary_);
    }
    if (isDeleted_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, isDeleted_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, name_);
    }
    if (nickName_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getNickName());
    }
    {
      int dataSize = 0;
      for (int i = 0; i < strLing_.size(); i++) {
        dataSize += computeStringSizeNoTag(strLing_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getStrLingList().size();
    }
    for (int i = 0; i < list_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, list_.get(i));
    }
    for (java.util.Map.Entry<String, String> entry
         : internalGetStrMap().getMap().entrySet()) {
      com.google.protobuf.MapEntry<String, String>
      strMap__ = StrMapDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(12, strMap__);
    }
    for (java.util.Map.Entry<String, UserMapPO> entry
         : internalGetObjMap().getMap().entrySet()) {
      com.google.protobuf.MapEntry<String, UserMapPO>
      objMap__ = ObjMapDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(13, objMap__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof User)) {
      return super.equals(obj);
    }
    User other = (User) obj;

    if (getId()
        != other.getId()) return false;
    if (getAge()
        != other.getAge()) return false;
    if (Float.floatToIntBits(getPrice())
        != Float.floatToIntBits(
            other.getPrice())) return false;
    if (Double.doubleToLongBits(getSalary())
        != Double.doubleToLongBits(
            other.getSalary())) return false;
    if (getIsDeleted()
        != other.getIsDeleted()) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (hasNickName() != other.hasNickName()) return false;
    if (hasNickName()) {
      if (!getNickName()
          .equals(other.getNickName())) return false;
    }
    if (!getStrLingList()
        .equals(other.getStrLingList())) return false;
    if (!getListList()
        .equals(other.getListList())) return false;
    if (!internalGetStrMap().equals(
        other.internalGetStrMap())) return false;
    if (!internalGetObjMap().equals(
        other.internalGetObjMap())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + AGE_FIELD_NUMBER;
    hash = (53 * hash) + getAge();
    hash = (37 * hash) + PRICE_FIELD_NUMBER;
    hash = (53 * hash) + Float.floatToIntBits(
        getPrice());
    hash = (37 * hash) + SALARY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        Double.doubleToLongBits(getSalary()));
    hash = (37 * hash) + ISDELETED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsDeleted());
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (hasNickName()) {
      hash = (37 * hash) + NICKNAME_FIELD_NUMBER;
      hash = (53 * hash) + getNickName().hashCode();
    }
    if (getStrLingCount() > 0) {
      hash = (37 * hash) + STRLING_FIELD_NUMBER;
      hash = (53 * hash) + getStrLingList().hashCode();
    }
    if (getListCount() > 0) {
      hash = (37 * hash) + LIST_FIELD_NUMBER;
      hash = (53 * hash) + getListList().hashCode();
    }
    if (!internalGetStrMap().getMap().isEmpty()) {
      hash = (37 * hash) + STRMAP_FIELD_NUMBER;
      hash = (53 * hash) + internalGetStrMap().hashCode();
    }
    if (!internalGetObjMap().getMap().isEmpty()) {
      hash = (37 * hash) + OBJMAP_FIELD_NUMBER;
      hash = (53 * hash) + internalGetObjMap().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static User parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static User parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static User parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static User parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static User parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static User parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static User parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static User parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static User parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static User parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static User parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static User parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(User prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *创建一个 User 对象
   * </pre>
   *
   * Protobuf type {@code com.zpb.protobuf.proto.user.User}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.zpb.protobuf.proto.user.User)
      UserOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return UserOutClass.internal_static_com_zpb_protobuf_proto_user_User_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 12:
          return internalGetStrMap();
        case 13:
          return internalGetObjMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 12:
          return internalGetMutableStrMap();
        case 13:
          return internalGetMutableObjMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return UserOutClass.internal_static_com_zpb_protobuf_proto_user_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              User.class, Builder.class);
    }

    // Construct using com.zpb.protobuf.proto.user.User.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getListFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      age_ = 0;

      price_ = 0F;

      salary_ = 0D;

      isDeleted_ = false;

      name_ = "";

      if (nickNameBuilder_ == null) {
        nickName_ = null;
      } else {
        nickName_ = null;
        nickNameBuilder_ = null;
      }
      strLing_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      if (listBuilder_ == null) {
        list_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        listBuilder_.clear();
      }
      internalGetMutableStrMap().clear();
      internalGetMutableObjMap().clear();
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return UserOutClass.internal_static_com_zpb_protobuf_proto_user_User_descriptor;
    }

    @Override
    public User getDefaultInstanceForType() {
      return User.getDefaultInstance();
    }

    @Override
    public User build() {
      User result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public User buildPartial() {
      User result = new User(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      result.age_ = age_;
      result.price_ = price_;
      result.salary_ = salary_;
      result.isDeleted_ = isDeleted_;
      result.name_ = name_;
      if (nickNameBuilder_ == null) {
        result.nickName_ = nickName_;
      } else {
        result.nickName_ = nickNameBuilder_.build();
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        strLing_ = strLing_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.strLing_ = strLing_;
      if (listBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          list_ = java.util.Collections.unmodifiableList(list_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.list_ = list_;
      } else {
        result.list_ = listBuilder_.build();
      }
      result.strMap_ = internalGetStrMap();
      result.strMap_.makeImmutable();
      result.objMap_ = internalGetObjMap();
      result.objMap_.makeImmutable();
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof User) {
        return mergeFrom((User)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(User other) {
      if (other == User.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (other.getAge() != 0) {
        setAge(other.getAge());
      }
      if (other.getPrice() != 0F) {
        setPrice(other.getPrice());
      }
      if (other.getSalary() != 0D) {
        setSalary(other.getSalary());
      }
      if (other.getIsDeleted() != false) {
        setIsDeleted(other.getIsDeleted());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.hasNickName()) {
        mergeNickName(other.getNickName());
      }
      if (!other.strLing_.isEmpty()) {
        if (strLing_.isEmpty()) {
          strLing_ = other.strLing_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureStrLingIsMutable();
          strLing_.addAll(other.strLing_);
        }
        onChanged();
      }
      if (listBuilder_ == null) {
        if (!other.list_.isEmpty()) {
          if (list_.isEmpty()) {
            list_ = other.list_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureListIsMutable();
            list_.addAll(other.list_);
          }
          onChanged();
        }
      } else {
        if (!other.list_.isEmpty()) {
          if (listBuilder_.isEmpty()) {
            listBuilder_.dispose();
            listBuilder_ = null;
            list_ = other.list_;
            bitField0_ = (bitField0_ & ~0x00000002);
            listBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getListFieldBuilder() : null;
          } else {
            listBuilder_.addAllMessages(other.list_);
          }
        }
      }
      internalGetMutableStrMap().mergeFrom(
          other.internalGetStrMap());
      internalGetMutableObjMap().mergeFrom(
          other.internalGetObjMap());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      User parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (User) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <pre>
     * int64
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @Override
    public long getId() {
      return id_;
    }
    /**
     * <pre>
     * int64
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * int64
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private int age_ ;
    /**
     * <pre>
     * int32
     * </pre>
     *
     * <code>int32 age = 2;</code>
     * @return The age.
     */
    @Override
    public int getAge() {
      return age_;
    }
    /**
     * <pre>
     * int32
     * </pre>
     *
     * <code>int32 age = 2;</code>
     * @param value The age to set.
     * @return This builder for chaining.
     */
    public Builder setAge(int value) {
      
      age_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * int32
     * </pre>
     *
     * <code>int32 age = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAge() {
      
      age_ = 0;
      onChanged();
      return this;
    }

    private float price_ ;
    /**
     * <pre>
     * float
     * </pre>
     *
     * <code>float price = 3;</code>
     * @return The price.
     */
    @Override
    public float getPrice() {
      return price_;
    }
    /**
     * <pre>
     * float
     * </pre>
     *
     * <code>float price = 3;</code>
     * @param value The price to set.
     * @return This builder for chaining.
     */
    public Builder setPrice(float value) {
      
      price_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * float
     * </pre>
     *
     * <code>float price = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrice() {
      
      price_ = 0F;
      onChanged();
      return this;
    }

    private double salary_ ;
    /**
     * <pre>
     * double
     * </pre>
     *
     * <code>double salary = 4;</code>
     * @return The salary.
     */
    @Override
    public double getSalary() {
      return salary_;
    }
    /**
     * <pre>
     * double
     * </pre>
     *
     * <code>double salary = 4;</code>
     * @param value The salary to set.
     * @return This builder for chaining.
     */
    public Builder setSalary(double value) {
      
      salary_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * double
     * </pre>
     *
     * <code>double salary = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSalary() {
      
      salary_ = 0D;
      onChanged();
      return this;
    }

    private boolean isDeleted_ ;
    /**
     * <pre>
     * bool
     * </pre>
     *
     * <code>bool isDeleted = 5;</code>
     * @return The isDeleted.
     */
    @Override
    public boolean getIsDeleted() {
      return isDeleted_;
    }
    /**
     * <pre>
     * bool
     * </pre>
     *
     * <code>bool isDeleted = 5;</code>
     * @param value The isDeleted to set.
     * @return This builder for chaining.
     */
    public Builder setIsDeleted(boolean value) {
      
      isDeleted_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * bool
     * </pre>
     *
     * <code>bool isDeleted = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsDeleted() {
      
      isDeleted_ = false;
      onChanged();
      return this;
    }

    private Object name_ = "";
    /**
     * <pre>
     * String
     * </pre>
     *
     * <code>string name = 6;</code>
     * @return The name.
     */
    public String getName() {
      Object ref = name_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * String
     * </pre>
     *
     * <code>string name = 6;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * String
     * </pre>
     *
     * <code>string name = 6;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * String
     * </pre>
     *
     * <code>string name = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * String
     * </pre>
     *
     * <code>string name = 6;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private NickName nickName_;
    private com.google.protobuf.SingleFieldBuilderV3<
        NickName, NickName.Builder, NickNameOrBuilder> nickNameBuilder_;
    /**
     * <pre>
     * 对象中引用-对象
     * </pre>
     *
     * <code>.com.zpb.protobuf.proto.user.NickName nickName = 9;</code>
     * @return Whether the nickName field is set.
     */
    public boolean hasNickName() {
      return nickNameBuilder_ != null || nickName_ != null;
    }
    /**
     * <pre>
     * 对象中引用-对象
     * </pre>
     *
     * <code>.com.zpb.protobuf.proto.user.NickName nickName = 9;</code>
     * @return The nickName.
     */
    public NickName getNickName() {
      if (nickNameBuilder_ == null) {
        return nickName_ == null ? NickName.getDefaultInstance() : nickName_;
      } else {
        return nickNameBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 对象中引用-对象
     * </pre>
     *
     * <code>.com.zpb.protobuf.proto.user.NickName nickName = 9;</code>
     */
    public Builder setNickName(NickName value) {
      if (nickNameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        nickName_ = value;
        onChanged();
      } else {
        nickNameBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 对象中引用-对象
     * </pre>
     *
     * <code>.com.zpb.protobuf.proto.user.NickName nickName = 9;</code>
     */
    public Builder setNickName(
        NickName.Builder builderForValue) {
      if (nickNameBuilder_ == null) {
        nickName_ = builderForValue.build();
        onChanged();
      } else {
        nickNameBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 对象中引用-对象
     * </pre>
     *
     * <code>.com.zpb.protobuf.proto.user.NickName nickName = 9;</code>
     */
    public Builder mergeNickName(NickName value) {
      if (nickNameBuilder_ == null) {
        if (nickName_ != null) {
          nickName_ =
            NickName.newBuilder(nickName_).mergeFrom(value).buildPartial();
        } else {
          nickName_ = value;
        }
        onChanged();
      } else {
        nickNameBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 对象中引用-对象
     * </pre>
     *
     * <code>.com.zpb.protobuf.proto.user.NickName nickName = 9;</code>
     */
    public Builder clearNickName() {
      if (nickNameBuilder_ == null) {
        nickName_ = null;
        onChanged();
      } else {
        nickName_ = null;
        nickNameBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 对象中引用-对象
     * </pre>
     *
     * <code>.com.zpb.protobuf.proto.user.NickName nickName = 9;</code>
     */
    public NickName.Builder getNickNameBuilder() {
      
      onChanged();
      return getNickNameFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 对象中引用-对象
     * </pre>
     *
     * <code>.com.zpb.protobuf.proto.user.NickName nickName = 9;</code>
     */
    public NickNameOrBuilder getNickNameOrBuilder() {
      if (nickNameBuilder_ != null) {
        return nickNameBuilder_.getMessageOrBuilder();
      } else {
        return nickName_ == null ?
            NickName.getDefaultInstance() : nickName_;
      }
    }
    /**
     * <pre>
     * 对象中引用-对象
     * </pre>
     *
     * <code>.com.zpb.protobuf.proto.user.NickName nickName = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        NickName, NickName.Builder, NickNameOrBuilder>
        getNickNameFieldBuilder() {
      if (nickNameBuilder_ == null) {
        nickNameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            NickName, NickName.Builder, NickNameOrBuilder>(
                getNickName(),
                getParentForChildren(),
                isClean());
        nickName_ = null;
      }
      return nickNameBuilder_;
    }

    private com.google.protobuf.LazyStringList strLing_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureStrLingIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        strLing_ = new com.google.protobuf.LazyStringArrayList(strLing_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     * 对象中引用-List&lt;string&gt;
     * </pre>
     *
     * <code>repeated string strLing = 10;</code>
     * @return A structure.list containing the strLing.
     */
    public com.google.protobuf.ProtocolStringList
        getStrLingList() {
      return strLing_.getUnmodifiableView();
    }
    /**
     * <pre>
     * 对象中引用-List&lt;string&gt;
     * </pre>
     *
     * <code>repeated string strLing = 10;</code>
     * @return The count of strLing.
     */
    public int getStrLingCount() {
      return strLing_.size();
    }
    /**
     * <pre>
     * 对象中引用-List&lt;string&gt;
     * </pre>
     *
     * <code>repeated string strLing = 10;</code>
     * @param index The index of the element to return.
     * @return The strLing at the given index.
     */
    public String getStrLing(int index) {
      return strLing_.get(index);
    }
    /**
     * <pre>
     * 对象中引用-List&lt;string&gt;
     * </pre>
     *
     * <code>repeated string strLing = 10;</code>
     * @param index The index of the value to return.
     * @return The bytes of the strLing at the given index.
     */
    public com.google.protobuf.ByteString
        getStrLingBytes(int index) {
      return strLing_.getByteString(index);
    }
    /**
     * <pre>
     * 对象中引用-List&lt;string&gt;
     * </pre>
     *
     * <code>repeated string strLing = 10;</code>
     * @param index The index to set the value at.
     * @param value The strLing to set.
     * @return This builder for chaining.
     */
    public Builder setStrLing(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureStrLingIsMutable();
      strLing_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 对象中引用-List&lt;string&gt;
     * </pre>
     *
     * <code>repeated string strLing = 10;</code>
     * @param value The strLing to add.
     * @return This builder for chaining.
     */
    public Builder addStrLing(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureStrLingIsMutable();
      strLing_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 对象中引用-List&lt;string&gt;
     * </pre>
     *
     * <code>repeated string strLing = 10;</code>
     * @param values The strLing to add.
     * @return This builder for chaining.
     */
    public Builder addAllStrLing(
        Iterable<String> values) {
      ensureStrLingIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, strLing_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 对象中引用-List&lt;string&gt;
     * </pre>
     *
     * <code>repeated string strLing = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearStrLing() {
      strLing_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 对象中引用-List&lt;string&gt;
     * </pre>
     *
     * <code>repeated string strLing = 10;</code>
     * @param value The bytes of the strLing to add.
     * @return This builder for chaining.
     */
    public Builder addStrLingBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureStrLingIsMutable();
      strLing_.add(value);
      onChanged();
      return this;
    }

    private java.util.List<com.zpb.protobuf.test.demo.Demo> list_ =
      java.util.Collections.emptyList();
    private void ensureListIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        list_ = new java.util.ArrayList<com.zpb.protobuf.test.demo.Demo>(list_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.zpb.protobuf.test.demo.Demo, com.zpb.protobuf.test.demo.Demo.Builder, com.zpb.protobuf.test.demo.DemoOrBuilder> listBuilder_;

    /**
     * <pre>
     * 对象中引用-List&lt;Object&gt;
     * </pre>
     *
     * <code>repeated .com.zpb.protobuf.proto.demo.Demo List = 11;</code>
     */
    public java.util.List<com.zpb.protobuf.test.demo.Demo> getListList() {
      if (listBuilder_ == null) {
        return java.util.Collections.unmodifiableList(list_);
      } else {
        return listBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 对象中引用-List&lt;Object&gt;
     * </pre>
     *
     * <code>repeated .com.zpb.protobuf.proto.demo.Demo List = 11;</code>
     */
    public int getListCount() {
      if (listBuilder_ == null) {
        return list_.size();
      } else {
        return listBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 对象中引用-List&lt;Object&gt;
     * </pre>
     *
     * <code>repeated .com.zpb.protobuf.proto.demo.Demo List = 11;</code>
     */
    public com.zpb.protobuf.test.demo.Demo getList(int index) {
      if (listBuilder_ == null) {
        return list_.get(index);
      } else {
        return listBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 对象中引用-List&lt;Object&gt;
     * </pre>
     *
     * <code>repeated .com.zpb.protobuf.proto.demo.Demo List = 11;</code>
     */
    public Builder setList(
        int index, com.zpb.protobuf.test.demo.Demo value) {
      if (listBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureListIsMutable();
        list_.set(index, value);
        onChanged();
      } else {
        listBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 对象中引用-List&lt;Object&gt;
     * </pre>
     *
     * <code>repeated .com.zpb.protobuf.proto.demo.Demo List = 11;</code>
     */
    public Builder setList(
        int index, com.zpb.protobuf.test.demo.Demo.Builder builderForValue) {
      if (listBuilder_ == null) {
        ensureListIsMutable();
        list_.set(index, builderForValue.build());
        onChanged();
      } else {
        listBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 对象中引用-List&lt;Object&gt;
     * </pre>
     *
     * <code>repeated .com.zpb.protobuf.proto.demo.Demo List = 11;</code>
     */
    public Builder addList(com.zpb.protobuf.test.demo.Demo value) {
      if (listBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureListIsMutable();
        list_.add(value);
        onChanged();
      } else {
        listBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 对象中引用-List&lt;Object&gt;
     * </pre>
     *
     * <code>repeated .com.zpb.protobuf.proto.demo.Demo List = 11;</code>
     */
    public Builder addList(
        int index, com.zpb.protobuf.test.demo.Demo value) {
      if (listBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureListIsMutable();
        list_.add(index, value);
        onChanged();
      } else {
        listBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 对象中引用-List&lt;Object&gt;
     * </pre>
     *
     * <code>repeated .com.zpb.protobuf.proto.demo.Demo List = 11;</code>
     */
    public Builder addList(
        com.zpb.protobuf.test.demo.Demo.Builder builderForValue) {
      if (listBuilder_ == null) {
        ensureListIsMutable();
        list_.add(builderForValue.build());
        onChanged();
      } else {
        listBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 对象中引用-List&lt;Object&gt;
     * </pre>
     *
     * <code>repeated .com.zpb.protobuf.proto.demo.Demo List = 11;</code>
     */
    public Builder addList(
        int index, com.zpb.protobuf.test.demo.Demo.Builder builderForValue) {
      if (listBuilder_ == null) {
        ensureListIsMutable();
        list_.add(index, builderForValue.build());
        onChanged();
      } else {
        listBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 对象中引用-List&lt;Object&gt;
     * </pre>
     *
     * <code>repeated .com.zpb.protobuf.proto.demo.Demo List = 11;</code>
     */
    public Builder addAllList(
        Iterable<? extends com.zpb.protobuf.test.demo.Demo> values) {
      if (listBuilder_ == null) {
        ensureListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, list_);
        onChanged();
      } else {
        listBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 对象中引用-List&lt;Object&gt;
     * </pre>
     *
     * <code>repeated .com.zpb.protobuf.proto.demo.Demo List = 11;</code>
     */
    public Builder clearList() {
      if (listBuilder_ == null) {
        list_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        listBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 对象中引用-List&lt;Object&gt;
     * </pre>
     *
     * <code>repeated .com.zpb.protobuf.proto.demo.Demo List = 11;</code>
     */
    public Builder removeList(int index) {
      if (listBuilder_ == null) {
        ensureListIsMutable();
        list_.remove(index);
        onChanged();
      } else {
        listBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 对象中引用-List&lt;Object&gt;
     * </pre>
     *
     * <code>repeated .com.zpb.protobuf.proto.demo.Demo List = 11;</code>
     */
    public com.zpb.protobuf.test.demo.Demo.Builder getListBuilder(
        int index) {
      return getListFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 对象中引用-List&lt;Object&gt;
     * </pre>
     *
     * <code>repeated .com.zpb.protobuf.proto.demo.Demo List = 11;</code>
     */
    public com.zpb.protobuf.test.demo.DemoOrBuilder getListOrBuilder(
        int index) {
      if (listBuilder_ == null) {
        return list_.get(index);  } else {
        return listBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 对象中引用-List&lt;Object&gt;
     * </pre>
     *
     * <code>repeated .com.zpb.protobuf.proto.demo.Demo List = 11;</code>
     */
    public java.util.List<? extends com.zpb.protobuf.test.demo.DemoOrBuilder>
         getListOrBuilderList() {
      if (listBuilder_ != null) {
        return listBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(list_);
      }
    }
    /**
     * <pre>
     * 对象中引用-List&lt;Object&gt;
     * </pre>
     *
     * <code>repeated .com.zpb.protobuf.proto.demo.Demo List = 11;</code>
     */
    public com.zpb.protobuf.test.demo.Demo.Builder addListBuilder() {
      return getListFieldBuilder().addBuilder(
          com.zpb.protobuf.test.demo.Demo.getDefaultInstance());
    }
    /**
     * <pre>
     * 对象中引用-List&lt;Object&gt;
     * </pre>
     *
     * <code>repeated .com.zpb.protobuf.proto.demo.Demo List = 11;</code>
     */
    public com.zpb.protobuf.test.demo.Demo.Builder addListBuilder(
        int index) {
      return getListFieldBuilder().addBuilder(
          index, com.zpb.protobuf.test.demo.Demo.getDefaultInstance());
    }
    /**
     * <pre>
     * 对象中引用-List&lt;Object&gt;
     * </pre>
     *
     * <code>repeated .com.zpb.protobuf.proto.demo.Demo List = 11;</code>
     */
    public java.util.List<com.zpb.protobuf.test.demo.Demo.Builder>
         getListBuilderList() {
      return getListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.zpb.protobuf.test.demo.Demo, com.zpb.protobuf.test.demo.Demo.Builder, com.zpb.protobuf.test.demo.DemoOrBuilder>
        getListFieldBuilder() {
      if (listBuilder_ == null) {
        listBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.zpb.protobuf.test.demo.Demo, com.zpb.protobuf.test.demo.Demo.Builder, com.zpb.protobuf.test.demo.DemoOrBuilder>(
                list_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        list_ = null;
      }
      return listBuilder_;
    }

    private com.google.protobuf.MapField<
        String, String> strMap_;
    private com.google.protobuf.MapField<String, String>
    internalGetStrMap() {
      if (strMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            StrMapDefaultEntryHolder.defaultEntry);
      }
      return strMap_;
    }
    private com.google.protobuf.MapField<String, String>
    internalGetMutableStrMap() {
      onChanged();;
      if (strMap_ == null) {
        strMap_ = com.google.protobuf.MapField.newMapField(
            StrMapDefaultEntryHolder.defaultEntry);
      }
      if (!strMap_.isMutable()) {
        strMap_ = strMap_.copy();
      }
      return strMap_;
    }

    public int getStrMapCount() {
      return internalGetStrMap().getMap().size();
    }
    /**
     * <pre>
     * 对象中引用-Map&lt;string,string&gt;
     * </pre>
     *
     * <code>map&lt;string, string&gt; strMap = 12;</code>
     */

    @Override
    public boolean containsStrMap(
        String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetStrMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getStrMapMap()} instead.
     */
    @Override
    @Deprecated
    public java.util.Map<String, String> getStrMap() {
      return getStrMapMap();
    }
    /**
     * <pre>
     * 对象中引用-Map&lt;string,string&gt;
     * </pre>
     *
     * <code>map&lt;string, string&gt; strMap = 12;</code>
     */
    @Override

    public java.util.Map<String, String> getStrMapMap() {
      return internalGetStrMap().getMap();
    }
    /**
     * <pre>
     * 对象中引用-Map&lt;string,string&gt;
     * </pre>
     *
     * <code>map&lt;string, string&gt; strMap = 12;</code>
     */
    @Override

    public String getStrMapOrDefault(
        String key,
        String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<String, String> map =
          internalGetStrMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * 对象中引用-Map&lt;string,string&gt;
     * </pre>
     *
     * <code>map&lt;string, string&gt; strMap = 12;</code>
     */
    @Override

    public String getStrMapOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<String, String> map =
          internalGetStrMap().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearStrMap() {
      internalGetMutableStrMap().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * 对象中引用-Map&lt;string,string&gt;
     * </pre>
     *
     * <code>map&lt;string, string&gt; strMap = 12;</code>
     */

    public Builder removeStrMap(
        String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableStrMap().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @Deprecated
    public java.util.Map<String, String>
    getMutableStrMap() {
      return internalGetMutableStrMap().getMutableMap();
    }
    /**
     * <pre>
     * 对象中引用-Map&lt;string,string&gt;
     * </pre>
     *
     * <code>map&lt;string, string&gt; strMap = 12;</code>
     */
    public Builder putStrMap(
        String key,
        String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) {
  throw new NullPointerException("map value");
}

      internalGetMutableStrMap().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <pre>
     * 对象中引用-Map&lt;string,string&gt;
     * </pre>
     *
     * <code>map&lt;string, string&gt; strMap = 12;</code>
     */

    public Builder putAllStrMap(
        java.util.Map<String, String> values) {
      internalGetMutableStrMap().getMutableMap()
          .putAll(values);
      return this;
    }

    private com.google.protobuf.MapField<
        String, UserMapPO> objMap_;
    private com.google.protobuf.MapField<String, UserMapPO>
    internalGetObjMap() {
      if (objMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ObjMapDefaultEntryHolder.defaultEntry);
      }
      return objMap_;
    }
    private com.google.protobuf.MapField<String, UserMapPO>
    internalGetMutableObjMap() {
      onChanged();;
      if (objMap_ == null) {
        objMap_ = com.google.protobuf.MapField.newMapField(
            ObjMapDefaultEntryHolder.defaultEntry);
      }
      if (!objMap_.isMutable()) {
        objMap_ = objMap_.copy();
      }
      return objMap_;
    }

    public int getObjMapCount() {
      return internalGetObjMap().getMap().size();
    }
    /**
     * <pre>
     * 对象中引用-Map&lt;string,Object&gt;
     * </pre>
     *
     * <code>map&lt;string, .com.zpb.protobuf.proto.user.UserMapPO&gt; objMap = 13;</code>
     */

    @Override
    public boolean containsObjMap(
        String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetObjMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getObjMapMap()} instead.
     */
    @Override
    @Deprecated
    public java.util.Map<String, UserMapPO> getObjMap() {
      return getObjMapMap();
    }
    /**
     * <pre>
     * 对象中引用-Map&lt;string,Object&gt;
     * </pre>
     *
     * <code>map&lt;string, .com.zpb.protobuf.proto.user.UserMapPO&gt; objMap = 13;</code>
     */
    @Override

    public java.util.Map<String, UserMapPO> getObjMapMap() {
      return internalGetObjMap().getMap();
    }
    /**
     * <pre>
     * 对象中引用-Map&lt;string,Object&gt;
     * </pre>
     *
     * <code>map&lt;string, .com.zpb.protobuf.proto.user.UserMapPO&gt; objMap = 13;</code>
     */
    @Override

    public UserMapPO getObjMapOrDefault(
        String key,
        UserMapPO defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<String, UserMapPO> map =
          internalGetObjMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * 对象中引用-Map&lt;string,Object&gt;
     * </pre>
     *
     * <code>map&lt;string, .com.zpb.protobuf.proto.user.UserMapPO&gt; objMap = 13;</code>
     */
    @Override

    public UserMapPO getObjMapOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<String, UserMapPO> map =
          internalGetObjMap().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearObjMap() {
      internalGetMutableObjMap().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * 对象中引用-Map&lt;string,Object&gt;
     * </pre>
     *
     * <code>map&lt;string, .com.zpb.protobuf.proto.user.UserMapPO&gt; objMap = 13;</code>
     */

    public Builder removeObjMap(
        String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableObjMap().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @Deprecated
    public java.util.Map<String, UserMapPO>
    getMutableObjMap() {
      return internalGetMutableObjMap().getMutableMap();
    }
    /**
     * <pre>
     * 对象中引用-Map&lt;string,Object&gt;
     * </pre>
     *
     * <code>map&lt;string, .com.zpb.protobuf.proto.user.UserMapPO&gt; objMap = 13;</code>
     */
    public Builder putObjMap(
        String key,
        UserMapPO value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) {
  throw new NullPointerException("map value");
}

      internalGetMutableObjMap().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <pre>
     * 对象中引用-Map&lt;string,Object&gt;
     * </pre>
     *
     * <code>map&lt;string, .com.zpb.protobuf.proto.user.UserMapPO&gt; objMap = 13;</code>
     */

    public Builder putAllObjMap(
        java.util.Map<String, UserMapPO> values) {
      internalGetMutableObjMap().getMutableMap()
          .putAll(values);
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.zpb.protobuf.proto.user.User)
  }

  // @@protoc_insertion_point(class_scope:com.zpb.protobuf.proto.user.User)
  private static final User DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new User();
  }

  public static User getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<User>
      PARSER = new com.google.protobuf.AbstractParser<User>() {
    @Override
    public User parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new User(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<User> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<User> getParserForType() {
    return PARSER;
  }

  @Override
  public User getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

