// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.zpb.protobuf.test.user;

public interface UserMapOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.zpb.protobuf.proto.user.UserMap)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * map 对象
   * </pre>
   *
   * <code>map&lt;int64, .com.zpb.protobuf.proto.user.UserMapPO&gt; userMap = 8;</code>
   */
  int getUserMapCount();
  /**
   * <pre>
   * map 对象
   * </pre>
   *
   * <code>map&lt;int64, .com.zpb.protobuf.proto.user.UserMapPO&gt; userMap = 8;</code>
   */
  boolean containsUserMap(
      long key);
  /**
   * Use {@link #getUserMapMap()} instead.
   */
  @Deprecated
  java.util.Map<Long, UserMapPO>
  getUserMap();
  /**
   * <pre>
   * map 对象
   * </pre>
   *
   * <code>map&lt;int64, .com.zpb.protobuf.proto.user.UserMapPO&gt; userMap = 8;</code>
   */
  java.util.Map<Long, UserMapPO>
  getUserMapMap();
  /**
   * <pre>
   * map 对象
   * </pre>
   *
   * <code>map&lt;int64, .com.zpb.protobuf.proto.user.UserMapPO&gt; userMap = 8;</code>
   */

  UserMapPO getUserMapOrDefault(
      long key,
      UserMapPO defaultValue);
  /**
   * <pre>
   * map 对象
   * </pre>
   *
   * <code>map&lt;int64, .com.zpb.protobuf.proto.user.UserMapPO&gt; userMap = 8;</code>
   */

  UserMapPO getUserMapOrThrow(
      long key);
}
