// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.zpb.protobuf.test.user;

public interface UserListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.zpb.protobuf.proto.user.UserList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * structure.list 对象
   * </pre>
   *
   * <code>repeated .com.zpb.protobuf.proto.user.User user = 7;</code>
   */
  java.util.List<User>
      getUserList();
  /**
   * <pre>
   * structure.list 对象
   * </pre>
   *
   * <code>repeated .com.zpb.protobuf.proto.user.User user = 7;</code>
   */
  User getUser(int index);
  /**
   * <pre>
   * structure.list 对象
   * </pre>
   *
   * <code>repeated .com.zpb.protobuf.proto.user.User user = 7;</code>
   */
  int getUserCount();
  /**
   * <pre>
   * structure.list 对象
   * </pre>
   *
   * <code>repeated .com.zpb.protobuf.proto.user.User user = 7;</code>
   */
  java.util.List<? extends UserOrBuilder>
      getUserOrBuilderList();
  /**
   * <pre>
   * structure.list 对象
   * </pre>
   *
   * <code>repeated .com.zpb.protobuf.proto.user.User user = 7;</code>
   */
  UserOrBuilder getUserOrBuilder(
      int index);
}
