// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package com.zpb.protobuf.test.hello;

public interface UserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>int64 age = 2;</code>
   * @return The age.
   */
  long getAge();

  /**
   * <code>string dept = 3;</code>
   * @return The dept.
   */
  java.lang.String getDept();
  /**
   * <code>string dept = 3;</code>
   * @return The bytes for dept.
   */
  com.google.protobuf.ByteString
      getDeptBytes();

  /**
   * <code>string job = 4;</code>
   * @return The job.
   */
  java.lang.String getJob();
  /**
   * <code>string job = 4;</code>
   * @return The bytes for job.
   */
  com.google.protobuf.ByteString
      getJobBytes();
}
