// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.zpb.protobuf.test.user;

/**
 * Protobuf type {@code com.zpb.protobuf.proto.user.UserList}
 */
public final class UserList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.zpb.protobuf.proto.user.UserList)
    UserListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UserList.newBuilder() to construct.
  private UserList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UserList() {
    user_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UserList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UserList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 58: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              user_ = new java.util.ArrayList<com.zpb.protobuf.test.user.User>();
              mutable_bitField0_ |= 0x00000001;
            }
            user_.add(
                input.readMessage(com.zpb.protobuf.test.user.User.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        user_ = java.util.Collections.unmodifiableList(user_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.zpb.protobuf.test.user.UserOutClass.internal_static_com_zpb_protobuf_proto_user_UserList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.zpb.protobuf.test.user.UserOutClass.internal_static_com_zpb_protobuf_proto_user_UserList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.zpb.protobuf.test.user.UserList.class, com.zpb.protobuf.test.user.UserList.Builder.class);
  }

  public static final int USER_FIELD_NUMBER = 7;
  private java.util.List<com.zpb.protobuf.test.user.User> user_;
  /**
   * <pre>
   * structure.list 对象
   * </pre>
   *
   * <code>repeated .com.zpb.protobuf.proto.user.User user = 7;</code>
   */
  @java.lang.Override
  public java.util.List<com.zpb.protobuf.test.user.User> getUserList() {
    return user_;
  }
  /**
   * <pre>
   * structure.list 对象
   * </pre>
   *
   * <code>repeated .com.zpb.protobuf.proto.user.User user = 7;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.zpb.protobuf.test.user.UserOrBuilder>
      getUserOrBuilderList() {
    return user_;
  }
  /**
   * <pre>
   * structure.list 对象
   * </pre>
   *
   * <code>repeated .com.zpb.protobuf.proto.user.User user = 7;</code>
   */
  @java.lang.Override
  public int getUserCount() {
    return user_.size();
  }
  /**
   * <pre>
   * structure.list 对象
   * </pre>
   *
   * <code>repeated .com.zpb.protobuf.proto.user.User user = 7;</code>
   */
  @java.lang.Override
  public com.zpb.protobuf.test.user.User getUser(int index) {
    return user_.get(index);
  }
  /**
   * <pre>
   * structure.list 对象
   * </pre>
   *
   * <code>repeated .com.zpb.protobuf.proto.user.User user = 7;</code>
   */
  @java.lang.Override
  public com.zpb.protobuf.test.user.UserOrBuilder getUserOrBuilder(
      int index) {
    return user_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < user_.size(); i++) {
      output.writeMessage(7, user_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < user_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, user_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.zpb.protobuf.test.user.UserList)) {
      return super.equals(obj);
    }
    com.zpb.protobuf.test.user.UserList other = (com.zpb.protobuf.test.user.UserList) obj;

    if (!getUserList()
        .equals(other.getUserList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getUserCount() > 0) {
      hash = (37 * hash) + USER_FIELD_NUMBER;
      hash = (53 * hash) + getUserList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.zpb.protobuf.test.user.UserList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zpb.protobuf.test.user.UserList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zpb.protobuf.test.user.UserList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zpb.protobuf.test.user.UserList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zpb.protobuf.test.user.UserList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zpb.protobuf.test.user.UserList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zpb.protobuf.test.user.UserList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zpb.protobuf.test.user.UserList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zpb.protobuf.test.user.UserList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.zpb.protobuf.test.user.UserList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zpb.protobuf.test.user.UserList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zpb.protobuf.test.user.UserList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.zpb.protobuf.test.user.UserList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.zpb.protobuf.proto.user.UserList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.zpb.protobuf.proto.user.UserList)
      com.zpb.protobuf.test.user.UserListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zpb.protobuf.test.user.UserOutClass.internal_static_com_zpb_protobuf_proto_user_UserList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zpb.protobuf.test.user.UserOutClass.internal_static_com_zpb_protobuf_proto_user_UserList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zpb.protobuf.test.user.UserList.class, com.zpb.protobuf.test.user.UserList.Builder.class);
    }

    // Construct using com.zpb.protobuf.proto.user.UserList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getUserFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (userBuilder_ == null) {
        user_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        userBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.zpb.protobuf.test.user.UserOutClass.internal_static_com_zpb_protobuf_proto_user_UserList_descriptor;
    }

    @java.lang.Override
    public com.zpb.protobuf.test.user.UserList getDefaultInstanceForType() {
      return com.zpb.protobuf.test.user.UserList.getDefaultInstance();
    }

    @java.lang.Override
    public com.zpb.protobuf.test.user.UserList build() {
      com.zpb.protobuf.test.user.UserList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.zpb.protobuf.test.user.UserList buildPartial() {
      com.zpb.protobuf.test.user.UserList result = new com.zpb.protobuf.test.user.UserList(this);
      int from_bitField0_ = bitField0_;
      if (userBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          user_ = java.util.Collections.unmodifiableList(user_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.user_ = user_;
      } else {
        result.user_ = userBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.zpb.protobuf.test.user.UserList) {
        return mergeFrom((com.zpb.protobuf.test.user.UserList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.zpb.protobuf.test.user.UserList other) {
      if (other == com.zpb.protobuf.test.user.UserList.getDefaultInstance()) return this;
      if (userBuilder_ == null) {
        if (!other.user_.isEmpty()) {
          if (user_.isEmpty()) {
            user_ = other.user_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureUserIsMutable();
            user_.addAll(other.user_);
          }
          onChanged();
        }
      } else {
        if (!other.user_.isEmpty()) {
          if (userBuilder_.isEmpty()) {
            userBuilder_.dispose();
            userBuilder_ = null;
            user_ = other.user_;
            bitField0_ = (bitField0_ & ~0x00000001);
            userBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getUserFieldBuilder() : null;
          } else {
            userBuilder_.addAllMessages(other.user_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.zpb.protobuf.test.user.UserList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.zpb.protobuf.test.user.UserList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.zpb.protobuf.test.user.User> user_ =
      java.util.Collections.emptyList();
    private void ensureUserIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        user_ = new java.util.ArrayList<com.zpb.protobuf.test.user.User>(user_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.zpb.protobuf.test.user.User, com.zpb.protobuf.test.user.User.Builder, com.zpb.protobuf.test.user.UserOrBuilder> userBuilder_;

    /**
     * <pre>
     * structure.list 对象
     * </pre>
     *
     * <code>repeated .com.zpb.protobuf.proto.user.User user = 7;</code>
     */
    public java.util.List<com.zpb.protobuf.test.user.User> getUserList() {
      if (userBuilder_ == null) {
        return java.util.Collections.unmodifiableList(user_);
      } else {
        return userBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * structure.list 对象
     * </pre>
     *
     * <code>repeated .com.zpb.protobuf.proto.user.User user = 7;</code>
     */
    public int getUserCount() {
      if (userBuilder_ == null) {
        return user_.size();
      } else {
        return userBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * structure.list 对象
     * </pre>
     *
     * <code>repeated .com.zpb.protobuf.proto.user.User user = 7;</code>
     */
    public com.zpb.protobuf.test.user.User getUser(int index) {
      if (userBuilder_ == null) {
        return user_.get(index);
      } else {
        return userBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * structure.list 对象
     * </pre>
     *
     * <code>repeated .com.zpb.protobuf.proto.user.User user = 7;</code>
     */
    public Builder setUser(
        int index, com.zpb.protobuf.test.user.User value) {
      if (userBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUserIsMutable();
        user_.set(index, value);
        onChanged();
      } else {
        userBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * structure.list 对象
     * </pre>
     *
     * <code>repeated .com.zpb.protobuf.proto.user.User user = 7;</code>
     */
    public Builder setUser(
        int index, com.zpb.protobuf.test.user.User.Builder builderForValue) {
      if (userBuilder_ == null) {
        ensureUserIsMutable();
        user_.set(index, builderForValue.build());
        onChanged();
      } else {
        userBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * structure.list 对象
     * </pre>
     *
     * <code>repeated .com.zpb.protobuf.proto.user.User user = 7;</code>
     */
    public Builder addUser(com.zpb.protobuf.test.user.User value) {
      if (userBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUserIsMutable();
        user_.add(value);
        onChanged();
      } else {
        userBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * structure.list 对象
     * </pre>
     *
     * <code>repeated .com.zpb.protobuf.proto.user.User user = 7;</code>
     */
    public Builder addUser(
        int index, com.zpb.protobuf.test.user.User value) {
      if (userBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUserIsMutable();
        user_.add(index, value);
        onChanged();
      } else {
        userBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * structure.list 对象
     * </pre>
     *
     * <code>repeated .com.zpb.protobuf.proto.user.User user = 7;</code>
     */
    public Builder addUser(
        com.zpb.protobuf.test.user.User.Builder builderForValue) {
      if (userBuilder_ == null) {
        ensureUserIsMutable();
        user_.add(builderForValue.build());
        onChanged();
      } else {
        userBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * structure.list 对象
     * </pre>
     *
     * <code>repeated .com.zpb.protobuf.proto.user.User user = 7;</code>
     */
    public Builder addUser(
        int index, com.zpb.protobuf.test.user.User.Builder builderForValue) {
      if (userBuilder_ == null) {
        ensureUserIsMutable();
        user_.add(index, builderForValue.build());
        onChanged();
      } else {
        userBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * structure.list 对象
     * </pre>
     *
     * <code>repeated .com.zpb.protobuf.proto.user.User user = 7;</code>
     */
    public Builder addAllUser(
        java.lang.Iterable<? extends com.zpb.protobuf.test.user.User> values) {
      if (userBuilder_ == null) {
        ensureUserIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, user_);
        onChanged();
      } else {
        userBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * structure.list 对象
     * </pre>
     *
     * <code>repeated .com.zpb.protobuf.proto.user.User user = 7;</code>
     */
    public Builder clearUser() {
      if (userBuilder_ == null) {
        user_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        userBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * structure.list 对象
     * </pre>
     *
     * <code>repeated .com.zpb.protobuf.proto.user.User user = 7;</code>
     */
    public Builder removeUser(int index) {
      if (userBuilder_ == null) {
        ensureUserIsMutable();
        user_.remove(index);
        onChanged();
      } else {
        userBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * structure.list 对象
     * </pre>
     *
     * <code>repeated .com.zpb.protobuf.proto.user.User user = 7;</code>
     */
    public com.zpb.protobuf.test.user.User.Builder getUserBuilder(
        int index) {
      return getUserFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * structure.list 对象
     * </pre>
     *
     * <code>repeated .com.zpb.protobuf.proto.user.User user = 7;</code>
     */
    public com.zpb.protobuf.test.user.UserOrBuilder getUserOrBuilder(
        int index) {
      if (userBuilder_ == null) {
        return user_.get(index);  } else {
        return userBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * structure.list 对象
     * </pre>
     *
     * <code>repeated .com.zpb.protobuf.proto.user.User user = 7;</code>
     */
    public java.util.List<? extends com.zpb.protobuf.test.user.UserOrBuilder>
         getUserOrBuilderList() {
      if (userBuilder_ != null) {
        return userBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(user_);
      }
    }
    /**
     * <pre>
     * structure.list 对象
     * </pre>
     *
     * <code>repeated .com.zpb.protobuf.proto.user.User user = 7;</code>
     */
    public com.zpb.protobuf.test.user.User.Builder addUserBuilder() {
      return getUserFieldBuilder().addBuilder(
          com.zpb.protobuf.test.user.User.getDefaultInstance());
    }
    /**
     * <pre>
     * structure.list 对象
     * </pre>
     *
     * <code>repeated .com.zpb.protobuf.proto.user.User user = 7;</code>
     */
    public com.zpb.protobuf.test.user.User.Builder addUserBuilder(
        int index) {
      return getUserFieldBuilder().addBuilder(
          index, com.zpb.protobuf.test.user.User.getDefaultInstance());
    }
    /**
     * <pre>
     * structure.list 对象
     * </pre>
     *
     * <code>repeated .com.zpb.protobuf.proto.user.User user = 7;</code>
     */
    public java.util.List<com.zpb.protobuf.test.user.User.Builder>
         getUserBuilderList() {
      return getUserFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.zpb.protobuf.test.user.User, com.zpb.protobuf.test.user.User.Builder, com.zpb.protobuf.test.user.UserOrBuilder>
        getUserFieldBuilder() {
      if (userBuilder_ == null) {
        userBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.zpb.protobuf.test.user.User, com.zpb.protobuf.test.user.User.Builder, com.zpb.protobuf.test.user.UserOrBuilder>(
                user_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        user_ = null;
      }
      return userBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.zpb.protobuf.proto.user.UserList)
  }

  // @@protoc_insertion_point(class_scope:com.zpb.protobuf.proto.user.UserList)
  private static final com.zpb.protobuf.test.user.UserList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.zpb.protobuf.test.user.UserList();
  }

  public static com.zpb.protobuf.test.user.UserList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserList>
      PARSER = new com.google.protobuf.AbstractParser<UserList>() {
    @java.lang.Override
    public UserList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UserList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UserList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.zpb.protobuf.test.user.UserList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

