// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.zpb.protobuf.test.user;

/**
 * Protobuf type {@code com.zpb.protobuf.proto.user.UserMap}
 */
public final class UserMap extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.zpb.protobuf.proto.user.UserMap)
    UserMapOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UserMap.newBuilder() to construct.
  private UserMap(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UserMap() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UserMap();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UserMap(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 66: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              userMap_ = com.google.protobuf.MapField.newMapField(
                  UserMapDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.Long, com.zpb.protobuf.test.user.UserMapPO>
            userMap__ = input.readMessage(
                UserMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            userMap_.getMutableMap().put(
                userMap__.getKey(), userMap__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.zpb.protobuf.test.user.UserOutClass.internal_static_com_zpb_protobuf_proto_user_UserMap_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 8:
        return internalGetUserMap();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.zpb.protobuf.test.user.UserOutClass.internal_static_com_zpb_protobuf_proto_user_UserMap_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.zpb.protobuf.test.user.UserMap.class, com.zpb.protobuf.test.user.UserMap.Builder.class);
  }

  public static final int USERMAP_FIELD_NUMBER = 8;
  private static final class UserMapDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.Long, com.zpb.protobuf.test.user.UserMapPO> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.Long, com.zpb.protobuf.test.user.UserMapPO>newDefaultInstance(
                com.zpb.protobuf.test.user.UserOutClass.internal_static_com_zpb_protobuf_proto_user_UserMap_UserMapEntry_descriptor,
                com.google.protobuf.WireFormat.FieldType.INT64,
                0L,
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                com.zpb.protobuf.test.user.UserMapPO.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.Long, com.zpb.protobuf.test.user.UserMapPO> userMap_;
  private com.google.protobuf.MapField<java.lang.Long, com.zpb.protobuf.test.user.UserMapPO>
  internalGetUserMap() {
    if (userMap_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          UserMapDefaultEntryHolder.defaultEntry);
    }
    return userMap_;
  }

  public int getUserMapCount() {
    return internalGetUserMap().getMap().size();
  }
  /**
   * <pre>
   * map 对象
   * </pre>
   *
   * <code>map&lt;int64, .com.zpb.protobuf.proto.user.UserMapPO&gt; userMap = 8;</code>
   */

  @java.lang.Override
  public boolean containsUserMap(
      long key) {
    
    return internalGetUserMap().getMap().containsKey(key);
  }
  /**
   * Use {@link #getUserMapMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.Long, com.zpb.protobuf.test.user.UserMapPO> getUserMap() {
    return getUserMapMap();
  }
  /**
   * <pre>
   * map 对象
   * </pre>
   *
   * <code>map&lt;int64, .com.zpb.protobuf.proto.user.UserMapPO&gt; userMap = 8;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.Long, com.zpb.protobuf.test.user.UserMapPO> getUserMapMap() {
    return internalGetUserMap().getMap();
  }
  /**
   * <pre>
   * map 对象
   * </pre>
   *
   * <code>map&lt;int64, .com.zpb.protobuf.proto.user.UserMapPO&gt; userMap = 8;</code>
   */
  @java.lang.Override

  public com.zpb.protobuf.test.user.UserMapPO getUserMapOrDefault(
      long key,
      com.zpb.protobuf.test.user.UserMapPO defaultValue) {
    
    java.util.Map<java.lang.Long, com.zpb.protobuf.test.user.UserMapPO> map =
        internalGetUserMap().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * map 对象
   * </pre>
   *
   * <code>map&lt;int64, .com.zpb.protobuf.proto.user.UserMapPO&gt; userMap = 8;</code>
   */
  @java.lang.Override

  public com.zpb.protobuf.test.user.UserMapPO getUserMapOrThrow(
      long key) {
    
    java.util.Map<java.lang.Long, com.zpb.protobuf.test.user.UserMapPO> map =
        internalGetUserMap().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeLongMapTo(
        output,
        internalGetUserMap(),
        UserMapDefaultEntryHolder.defaultEntry,
        8);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.Long, com.zpb.protobuf.test.user.UserMapPO> entry
         : internalGetUserMap().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Long, com.zpb.protobuf.test.user.UserMapPO>
      userMap__ = UserMapDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, userMap__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.zpb.protobuf.test.user.UserMap)) {
      return super.equals(obj);
    }
    com.zpb.protobuf.test.user.UserMap other = (com.zpb.protobuf.test.user.UserMap) obj;

    if (!internalGetUserMap().equals(
        other.internalGetUserMap())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetUserMap().getMap().isEmpty()) {
      hash = (37 * hash) + USERMAP_FIELD_NUMBER;
      hash = (53 * hash) + internalGetUserMap().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.zpb.protobuf.test.user.UserMap parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zpb.protobuf.test.user.UserMap parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zpb.protobuf.test.user.UserMap parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zpb.protobuf.test.user.UserMap parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zpb.protobuf.test.user.UserMap parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zpb.protobuf.test.user.UserMap parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zpb.protobuf.test.user.UserMap parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zpb.protobuf.test.user.UserMap parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zpb.protobuf.test.user.UserMap parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.zpb.protobuf.test.user.UserMap parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zpb.protobuf.test.user.UserMap parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zpb.protobuf.test.user.UserMap parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.zpb.protobuf.test.user.UserMap prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.zpb.protobuf.proto.user.UserMap}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.zpb.protobuf.proto.user.UserMap)
      com.zpb.protobuf.test.user.UserMapOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zpb.protobuf.test.user.UserOutClass.internal_static_com_zpb_protobuf_proto_user_UserMap_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 8:
          return internalGetUserMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 8:
          return internalGetMutableUserMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zpb.protobuf.test.user.UserOutClass.internal_static_com_zpb_protobuf_proto_user_UserMap_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zpb.protobuf.test.user.UserMap.class, com.zpb.protobuf.test.user.UserMap.Builder.class);
    }

    // Construct using com.zpb.protobuf.proto.user.UserMap.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      internalGetMutableUserMap().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.zpb.protobuf.test.user.UserOutClass.internal_static_com_zpb_protobuf_proto_user_UserMap_descriptor;
    }

    @java.lang.Override
    public com.zpb.protobuf.test.user.UserMap getDefaultInstanceForType() {
      return com.zpb.protobuf.test.user.UserMap.getDefaultInstance();
    }

    @java.lang.Override
    public com.zpb.protobuf.test.user.UserMap build() {
      com.zpb.protobuf.test.user.UserMap result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.zpb.protobuf.test.user.UserMap buildPartial() {
      com.zpb.protobuf.test.user.UserMap result = new com.zpb.protobuf.test.user.UserMap(this);
      int from_bitField0_ = bitField0_;
      result.userMap_ = internalGetUserMap();
      result.userMap_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.zpb.protobuf.test.user.UserMap) {
        return mergeFrom((com.zpb.protobuf.test.user.UserMap)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.zpb.protobuf.test.user.UserMap other) {
      if (other == com.zpb.protobuf.test.user.UserMap.getDefaultInstance()) return this;
      internalGetMutableUserMap().mergeFrom(
          other.internalGetUserMap());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.zpb.protobuf.test.user.UserMap parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.zpb.protobuf.test.user.UserMap) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.Long, com.zpb.protobuf.test.user.UserMapPO> userMap_;
    private com.google.protobuf.MapField<java.lang.Long, com.zpb.protobuf.test.user.UserMapPO>
    internalGetUserMap() {
      if (userMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            UserMapDefaultEntryHolder.defaultEntry);
      }
      return userMap_;
    }
    private com.google.protobuf.MapField<java.lang.Long, com.zpb.protobuf.test.user.UserMapPO>
    internalGetMutableUserMap() {
      onChanged();;
      if (userMap_ == null) {
        userMap_ = com.google.protobuf.MapField.newMapField(
            UserMapDefaultEntryHolder.defaultEntry);
      }
      if (!userMap_.isMutable()) {
        userMap_ = userMap_.copy();
      }
      return userMap_;
    }

    public int getUserMapCount() {
      return internalGetUserMap().getMap().size();
    }
    /**
     * <pre>
     * map 对象
     * </pre>
     *
     * <code>map&lt;int64, .com.zpb.protobuf.proto.user.UserMapPO&gt; userMap = 8;</code>
     */

    @java.lang.Override
    public boolean containsUserMap(
        long key) {
      
      return internalGetUserMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getUserMapMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Long, com.zpb.protobuf.test.user.UserMapPO> getUserMap() {
      return getUserMapMap();
    }
    /**
     * <pre>
     * map 对象
     * </pre>
     *
     * <code>map&lt;int64, .com.zpb.protobuf.proto.user.UserMapPO&gt; userMap = 8;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.Long, com.zpb.protobuf.test.user.UserMapPO> getUserMapMap() {
      return internalGetUserMap().getMap();
    }
    /**
     * <pre>
     * map 对象
     * </pre>
     *
     * <code>map&lt;int64, .com.zpb.protobuf.proto.user.UserMapPO&gt; userMap = 8;</code>
     */
    @java.lang.Override

    public com.zpb.protobuf.test.user.UserMapPO getUserMapOrDefault(
        long key,
        com.zpb.protobuf.test.user.UserMapPO defaultValue) {
      
      java.util.Map<java.lang.Long, com.zpb.protobuf.test.user.UserMapPO> map =
          internalGetUserMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * map 对象
     * </pre>
     *
     * <code>map&lt;int64, .com.zpb.protobuf.proto.user.UserMapPO&gt; userMap = 8;</code>
     */
    @java.lang.Override

    public com.zpb.protobuf.test.user.UserMapPO getUserMapOrThrow(
        long key) {
      
      java.util.Map<java.lang.Long, com.zpb.protobuf.test.user.UserMapPO> map =
          internalGetUserMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearUserMap() {
      internalGetMutableUserMap().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * map 对象
     * </pre>
     *
     * <code>map&lt;int64, .com.zpb.protobuf.proto.user.UserMapPO&gt; userMap = 8;</code>
     */

    public Builder removeUserMap(
        long key) {
      
      internalGetMutableUserMap().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Long, com.zpb.protobuf.test.user.UserMapPO>
    getMutableUserMap() {
      return internalGetMutableUserMap().getMutableMap();
    }
    /**
     * <pre>
     * map 对象
     * </pre>
     *
     * <code>map&lt;int64, .com.zpb.protobuf.proto.user.UserMapPO&gt; userMap = 8;</code>
     */
    public Builder putUserMap(
        long key,
        com.zpb.protobuf.test.user.UserMapPO value) {
      
      if (value == null) {
  throw new NullPointerException("map value");
}

      internalGetMutableUserMap().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <pre>
     * map 对象
     * </pre>
     *
     * <code>map&lt;int64, .com.zpb.protobuf.proto.user.UserMapPO&gt; userMap = 8;</code>
     */

    public Builder putAllUserMap(
        java.util.Map<java.lang.Long, com.zpb.protobuf.test.user.UserMapPO> values) {
      internalGetMutableUserMap().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.zpb.protobuf.proto.user.UserMap)
  }

  // @@protoc_insertion_point(class_scope:com.zpb.protobuf.proto.user.UserMap)
  private static final com.zpb.protobuf.test.user.UserMap DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.zpb.protobuf.test.user.UserMap();
  }

  public static com.zpb.protobuf.test.user.UserMap getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserMap>
      PARSER = new com.google.protobuf.AbstractParser<UserMap>() {
    @java.lang.Override
    public UserMap parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UserMap(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UserMap> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserMap> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.zpb.protobuf.test.user.UserMap getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

