// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.zpb.protobuf.test.user;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.zpb.protobuf.proto.user.User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * int64
   * </pre>
   *
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <pre>
   * int32
   * </pre>
   *
   * <code>int32 age = 2;</code>
   * @return The age.
   */
  int getAge();

  /**
   * <pre>
   * float
   * </pre>
   *
   * <code>float price = 3;</code>
   * @return The price.
   */
  float getPrice();

  /**
   * <pre>
   * double
   * </pre>
   *
   * <code>double salary = 4;</code>
   * @return The salary.
   */
  double getSalary();

  /**
   * <pre>
   * bool
   * </pre>
   *
   * <code>bool isDeleted = 5;</code>
   * @return The isDeleted.
   */
  boolean getIsDeleted();

  /**
   * <pre>
   * String
   * </pre>
   *
   * <code>string name = 6;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * String
   * </pre>
   *
   * <code>string name = 6;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * 对象中引用-对象
   * </pre>
   *
   * <code>.com.zpb.protobuf.proto.user.NickName nickName = 9;</code>
   * @return Whether the nickName field is set.
   */
  boolean hasNickName();
  /**
   * <pre>
   * 对象中引用-对象
   * </pre>
   *
   * <code>.com.zpb.protobuf.proto.user.NickName nickName = 9;</code>
   * @return The nickName.
   */
  com.zpb.protobuf.test.user.NickName getNickName();
  /**
   * <pre>
   * 对象中引用-对象
   * </pre>
   *
   * <code>.com.zpb.protobuf.proto.user.NickName nickName = 9;</code>
   */
  com.zpb.protobuf.test.user.NickNameOrBuilder getNickNameOrBuilder();

  /**
   * <pre>
   * 对象中引用-List&lt;string&gt;
   * </pre>
   *
   * <code>repeated string strLing = 10;</code>
   * @return A structure.list containing the strLing.
   */
  java.util.List<java.lang.String>
      getStrLingList();
  /**
   * <pre>
   * 对象中引用-List&lt;string&gt;
   * </pre>
   *
   * <code>repeated string strLing = 10;</code>
   * @return The count of strLing.
   */
  int getStrLingCount();
  /**
   * <pre>
   * 对象中引用-List&lt;string&gt;
   * </pre>
   *
   * <code>repeated string strLing = 10;</code>
   * @param index The index of the element to return.
   * @return The strLing at the given index.
   */
  java.lang.String getStrLing(int index);
  /**
   * <pre>
   * 对象中引用-List&lt;string&gt;
   * </pre>
   *
   * <code>repeated string strLing = 10;</code>
   * @param index The index of the value to return.
   * @return The bytes of the strLing at the given index.
   */
  com.google.protobuf.ByteString
      getStrLingBytes(int index);

  /**
   * <pre>
   * 对象中引用-List&lt;Object&gt;
   * </pre>
   *
   * <code>repeated .com.zpb.protobuf.proto.demo.Demo List = 11;</code>
   */
  java.util.List<com.zpb.protobuf.test.demo.Demo>
      getListList();
  /**
   * <pre>
   * 对象中引用-List&lt;Object&gt;
   * </pre>
   *
   * <code>repeated .com.zpb.protobuf.proto.demo.Demo List = 11;</code>
   */
  com.zpb.protobuf.test.demo.Demo getList(int index);
  /**
   * <pre>
   * 对象中引用-List&lt;Object&gt;
   * </pre>
   *
   * <code>repeated .com.zpb.protobuf.proto.demo.Demo List = 11;</code>
   */
  int getListCount();
  /**
   * <pre>
   * 对象中引用-List&lt;Object&gt;
   * </pre>
   *
   * <code>repeated .com.zpb.protobuf.proto.demo.Demo List = 11;</code>
   */
  java.util.List<? extends com.zpb.protobuf.test.demo.DemoOrBuilder>
      getListOrBuilderList();
  /**
   * <pre>
   * 对象中引用-List&lt;Object&gt;
   * </pre>
   *
   * <code>repeated .com.zpb.protobuf.proto.demo.Demo List = 11;</code>
   */
  com.zpb.protobuf.test.demo.DemoOrBuilder getListOrBuilder(
      int index);

  /**
   * <pre>
   * 对象中引用-Map&lt;string,string&gt;
   * </pre>
   *
   * <code>map&lt;string, string&gt; strMap = 12;</code>
   */
  int getStrMapCount();
  /**
   * <pre>
   * 对象中引用-Map&lt;string,string&gt;
   * </pre>
   *
   * <code>map&lt;string, string&gt; strMap = 12;</code>
   */
  boolean containsStrMap(
      java.lang.String key);
  /**
   * Use {@link #getStrMapMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getStrMap();
  /**
   * <pre>
   * 对象中引用-Map&lt;string,string&gt;
   * </pre>
   *
   * <code>map&lt;string, string&gt; strMap = 12;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getStrMapMap();
  /**
   * <pre>
   * 对象中引用-Map&lt;string,string&gt;
   * </pre>
   *
   * <code>map&lt;string, string&gt; strMap = 12;</code>
   */

  java.lang.String getStrMapOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <pre>
   * 对象中引用-Map&lt;string,string&gt;
   * </pre>
   *
   * <code>map&lt;string, string&gt; strMap = 12;</code>
   */

  java.lang.String getStrMapOrThrow(
      java.lang.String key);

  /**
   * <pre>
   * 对象中引用-Map&lt;string,Object&gt;
   * </pre>
   *
   * <code>map&lt;string, .com.zpb.protobuf.proto.user.UserMapPO&gt; objMap = 13;</code>
   */
  int getObjMapCount();
  /**
   * <pre>
   * 对象中引用-Map&lt;string,Object&gt;
   * </pre>
   *
   * <code>map&lt;string, .com.zpb.protobuf.proto.user.UserMapPO&gt; objMap = 13;</code>
   */
  boolean containsObjMap(
      java.lang.String key);
  /**
   * Use {@link #getObjMapMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.zpb.protobuf.test.user.UserMapPO>
  getObjMap();
  /**
   * <pre>
   * 对象中引用-Map&lt;string,Object&gt;
   * </pre>
   *
   * <code>map&lt;string, .com.zpb.protobuf.proto.user.UserMapPO&gt; objMap = 13;</code>
   */
  java.util.Map<java.lang.String, com.zpb.protobuf.test.user.UserMapPO>
  getObjMapMap();
  /**
   * <pre>
   * 对象中引用-Map&lt;string,Object&gt;
   * </pre>
   *
   * <code>map&lt;string, .com.zpb.protobuf.proto.user.UserMapPO&gt; objMap = 13;</code>
   */

  com.zpb.protobuf.test.user.UserMapPO getObjMapOrDefault(
      java.lang.String key,
      com.zpb.protobuf.test.user.UserMapPO defaultValue);
  /**
   * <pre>
   * 对象中引用-Map&lt;string,Object&gt;
   * </pre>
   *
   * <code>map&lt;string, .com.zpb.protobuf.proto.user.UserMapPO&gt; objMap = 13;</code>
   */

  com.zpb.protobuf.test.user.UserMapPO getObjMapOrThrow(
      java.lang.String key);
}
