// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.zpb.protobuf.test.user;

public final class UserOutClass {
  private UserOutClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zpb_protobuf_proto_user_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zpb_protobuf_proto_user_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zpb_protobuf_proto_user_User_StrMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zpb_protobuf_proto_user_User_StrMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zpb_protobuf_proto_user_User_ObjMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zpb_protobuf_proto_user_User_ObjMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zpb_protobuf_proto_user_UserList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zpb_protobuf_proto_user_UserList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zpb_protobuf_proto_user_UserMap_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zpb_protobuf_proto_user_UserMap_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zpb_protobuf_proto_user_UserMap_UserMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zpb_protobuf_proto_user_UserMap_UserMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zpb_protobuf_proto_user_UserMapPO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zpb_protobuf_proto_user_UserMapPO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zpb_protobuf_proto_user_NickName_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zpb_protobuf_proto_user_NickName_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\033com.zpb.protobuf.proto.use" +
      "r\032\ndemo.proto\"\336\003\n\004User\022\n\n\002id\030\001 \001(\003\022\013\n\003ag" +
      "e\030\002 \001(\005\022\r\n\005price\030\003 \001(\002\022\016\n\006salary\030\004 \001(\001\022\021" +
      "\n\tisDeleted\030\005 \001(\010\022\014\n\004name\030\006 \001(\t\0227\n\010nickN" +
      "ame\030\t \001(\0132%.com.zpb.protobuf.proto.user." +
      "NickName\022\017\n\007strLing\030\n \003(\t\022/\n\004List\030\013 \003(\0132" +
      "!.com.zpb.protobuf.proto.demo.Demo\022=\n\006st" +
      "rMap\030\014 \003(\0132-.com.zpb.protobuf.proto.user" +
      ".User.StrMapEntry\022=\n\006objMap\030\r \003(\0132-.com." +
      "zpb.protobuf.proto.user.User.ObjMapEntry" +
      "\032-\n\013StrMapEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 " +
      "\001(\t:\0028\001\032U\n\013ObjMapEntry\022\013\n\003key\030\001 \001(\t\0225\n\005v" +
      "alue\030\002 \001(\0132&.com.zpb.protobuf.proto.user" +
      ".UserMapPO:\0028\001\";\n\010UserList\022/\n\004user\030\007 \003(\013" +
      "2!.com.zpb.protobuf.proto.user.User\"\245\001\n\007" +
      "UserMap\022B\n\007userMap\030\010 \003(\01321.com.zpb.proto" +
      "buf.proto.user.UserMap.UserMapEntry\032V\n\014U" +
      "serMapEntry\022\013\n\003key\030\001 \001(\003\0225\n\005value\030\002 \001(\0132" +
      "&.com.zpb.protobuf.proto.user.UserMapPO:" +
      "\0028\001\"H\n\tUserMapPO\022\n\n\002id\030\001 \001(\003\022/\n\004user\030\007 \001" +
      "(\0132!.com.zpb.protobuf.proto.user.User\"\034\n" +
      "\010NickName\022\020\n\010nickName\030\006 \001(\tB0\n\033com.zpb.p" +
      "rotobuf.proto.userB\014UserOutClassP\001\240\001\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.zpb.protobuf.test.demo.DemoProto.getDescriptor(),
        });
    internal_static_com_zpb_protobuf_proto_user_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_zpb_protobuf_proto_user_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zpb_protobuf_proto_user_User_descriptor,
        new java.lang.String[] { "Id", "Age", "Price", "Salary", "IsDeleted", "Name", "NickName", "StrLing", "List", "StrMap", "ObjMap", });
    internal_static_com_zpb_protobuf_proto_user_User_StrMapEntry_descriptor =
      internal_static_com_zpb_protobuf_proto_user_User_descriptor.getNestedTypes().get(0);
    internal_static_com_zpb_protobuf_proto_user_User_StrMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zpb_protobuf_proto_user_User_StrMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_zpb_protobuf_proto_user_User_ObjMapEntry_descriptor =
      internal_static_com_zpb_protobuf_proto_user_User_descriptor.getNestedTypes().get(1);
    internal_static_com_zpb_protobuf_proto_user_User_ObjMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zpb_protobuf_proto_user_User_ObjMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_zpb_protobuf_proto_user_UserList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_zpb_protobuf_proto_user_UserList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zpb_protobuf_proto_user_UserList_descriptor,
        new java.lang.String[] { "User", });
    internal_static_com_zpb_protobuf_proto_user_UserMap_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_zpb_protobuf_proto_user_UserMap_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zpb_protobuf_proto_user_UserMap_descriptor,
        new java.lang.String[] { "UserMap", });
    internal_static_com_zpb_protobuf_proto_user_UserMap_UserMapEntry_descriptor =
      internal_static_com_zpb_protobuf_proto_user_UserMap_descriptor.getNestedTypes().get(0);
    internal_static_com_zpb_protobuf_proto_user_UserMap_UserMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zpb_protobuf_proto_user_UserMap_UserMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_zpb_protobuf_proto_user_UserMapPO_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_zpb_protobuf_proto_user_UserMapPO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zpb_protobuf_proto_user_UserMapPO_descriptor,
        new java.lang.String[] { "Id", "User", });
    internal_static_com_zpb_protobuf_proto_user_NickName_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_zpb_protobuf_proto_user_NickName_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zpb_protobuf_proto_user_NickName_descriptor,
        new java.lang.String[] { "NickName", });
    com.zpb.protobuf.test.demo.DemoProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
