// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.zpb.protobuf.test.user;

public interface UserMapPOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.zpb.protobuf.proto.user.UserMapPO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>.com.zpb.protobuf.proto.user.User user = 7;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.com.zpb.protobuf.proto.user.User user = 7;</code>
   * @return The user.
   */
  com.zpb.protobuf.test.user.User getUser();
  /**
   * <code>.com.zpb.protobuf.proto.user.User user = 7;</code>
   */
  com.zpb.protobuf.test.user.UserOrBuilder getUserOrBuilder();
}
