// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package com.zpb.protobuf.test.demo;

public final class DemoProto {
  private DemoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zpb_protobuf_proto_demo_Demo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zpb_protobuf_proto_demo_Demo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zpb_protobuf_proto_demo_RequestDemo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zpb_protobuf_proto_demo_RequestDemo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\ndemo.proto\022\033com.zpb.protobuf.proto.dem" +
      "o\">\n\004Demo\022\n\n\002id\030\001 \001(\003\022\013\n\003age\030\002 \001(\005\022\014\n\004na" +
      "me\030\003 \001(\t\022\017\n\007address\030\004 \001(\t\"\031\n\013RequestDemo" +
      "\022\n\n\002id\030\001 \001(\0032e\n\013DemoService\022V\n\007getDemo\022(" +
      ".com.zpb.protobuf.proto.demo.RequestDemo" +
      "\032!.com.zpb.protobuf.proto.demo.DemoB0\n\033c" +
      "om.zpb.protobuf.proto.demoB\tDemoProtoP\001\210" +
      "\001\001\240\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_zpb_protobuf_proto_demo_Demo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_zpb_protobuf_proto_demo_Demo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zpb_protobuf_proto_demo_Demo_descriptor,
        new String[] { "Id", "Age", "Name", "Address", });
    internal_static_com_zpb_protobuf_proto_demo_RequestDemo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_zpb_protobuf_proto_demo_RequestDemo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zpb_protobuf_proto_demo_RequestDemo_descriptor,
        new String[] { "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
