// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package com.zpb.protobuf.test.hello;

@SuppressWarnings("all")
public final class User {
  private User() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor internal_static_UserRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_UserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor internal_static_UserResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_UserResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor descriptor;
  static {
    String[] descriptorData = {
      "\n\013hello.proto\"\037\n\013UserRequest\022\020\n\010username" +
      "\030\001 \001(\t\"H\n\014UserResponse\022\020\n\010username\030\001 \001(\t" +
      "\022\013\n\003age\030\002 \001(\003\022\014\n\004dept\030\003 \001(\t\022\013\n\003job\030\004 \001(\t" +
      "B&\n\034com.zpb.protobuf.proto.helloB\004UserP\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_UserRequest_descriptor = getDescriptor().getMessageTypes().get(0);
    internal_static_UserRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserRequest_descriptor,
        new String[] { "Username", });
    internal_static_UserResponse_descriptor = getDescriptor().getMessageTypes().get(1);
    internal_static_UserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserResponse_descriptor,
        new String[] { "Username", "Age", "Dept", "Job", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
