// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package com.zpb.protobuf.test.demo;

/**
 * Protobuf service {@code com.zpb.protobuf.proto.demo.DemoService}
 */
public  abstract class DemoService
    implements com.google.protobuf.Service {
  protected DemoService() {}

  public interface Interface {
    /**
     * <code>rpc getDemo(.com.zpb.protobuf.proto.demo.RequestDemo) returns (.com.zpb.protobuf.proto.demo.Demo);</code>
     */
    public abstract void getDemo(
        com.google.protobuf.RpcController controller,
        com.zpb.protobuf.test.demo.RequestDemo request,
        com.google.protobuf.RpcCallback<com.zpb.protobuf.test.demo.Demo> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new DemoService() {
      @java.lang.Override
      public  void getDemo(
          com.google.protobuf.RpcController controller,
          com.zpb.protobuf.test.demo.RequestDemo request,
          com.google.protobuf.RpcCallback<com.zpb.protobuf.test.demo.Demo> done) {
        impl.getDemo(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.getDemo(controller, (com.zpb.protobuf.test.demo.RequestDemo)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.zpb.protobuf.test.demo.RequestDemo.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.zpb.protobuf.test.demo.Demo.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <code>rpc getDemo(.com.zpb.protobuf.proto.demo.RequestDemo) returns (.com.zpb.protobuf.proto.demo.Demo);</code>
   */
  public abstract void getDemo(
      com.google.protobuf.RpcController controller,
      com.zpb.protobuf.test.demo.RequestDemo request,
      com.google.protobuf.RpcCallback<com.zpb.protobuf.test.demo.Demo> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return com.zpb.protobuf.test.demo.DemoProto.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.getDemo(controller, (com.zpb.protobuf.test.demo.RequestDemo)request,
          com.google.protobuf.RpcUtil.<com.zpb.protobuf.test.demo.Demo>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.zpb.protobuf.test.demo.RequestDemo.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.zpb.protobuf.test.demo.Demo.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends com.zpb.protobuf.test.demo.DemoService implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void getDemo(
        com.google.protobuf.RpcController controller,
        com.zpb.protobuf.test.demo.RequestDemo request,
        com.google.protobuf.RpcCallback<com.zpb.protobuf.test.demo.Demo> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.zpb.protobuf.test.demo.Demo.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.zpb.protobuf.test.demo.Demo.class,
          com.zpb.protobuf.test.demo.Demo.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public com.zpb.protobuf.test.demo.Demo getDemo(
        com.google.protobuf.RpcController controller,
        com.zpb.protobuf.test.demo.RequestDemo request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public com.zpb.protobuf.test.demo.Demo getDemo(
        com.google.protobuf.RpcController controller,
        com.zpb.protobuf.test.demo.RequestDemo request)
        throws com.google.protobuf.ServiceException {
      return (com.zpb.protobuf.test.demo.Demo) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.zpb.protobuf.test.demo.Demo.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:com.zpb.protobuf.proto.demo.DemoService)
}

