// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package com.zpb.protobuf.test.demo;

public interface RequestDemoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.zpb.protobuf.proto.demo.RequestDemo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
